[package]
name = "line"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
roblib-client = { git="https://github.com/kareszklub/roblib-rs", features = ["roland"] }
